development:
  adapter: postgresql
  encoding: unicode
  database: TCC_development
  pool: 5
  username: guilherme
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  database: TCC_test
  pool: 5
  username: guilherme
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: TCC_production
  pool: 5
  username: guilherme
  password: postgres

cucumber:
  <<: *test
