development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: TCC_development1
  pool: 5
  username: postgres
  password: vhorghan

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: TCC_test
  pool: 5
  username: postgres
  password: vhorghan

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: TCC_production
  pool: 5
  username: postgres
  password: vhorghan

cucumber:
  <<: *test
